### YamlMime:ManagedReference
items:
- uid: Genesis.Graphics.RenderSettings
  commentId: T:Genesis.Graphics.RenderSettings
  id: RenderSettings
  parent: Genesis.Graphics
  children:
  - Genesis.Graphics.RenderSettings.VirtualResolution
  - Genesis.Graphics.RenderSettings.gamma
  langs:
  - csharp
  - vb
  name: RenderSettings
  nameWithType: RenderSettings
  fullName: Genesis.Graphics.RenderSettings
  type: Struct
  assemblies:
  - Genesis
  namespace: Genesis.Graphics
  syntax:
    content: public struct RenderSettings
    content.vb: Public Structure RenderSettings
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetType
- uid: Genesis.Graphics.RenderSettings.gamma
  commentId: F:Genesis.Graphics.RenderSettings.gamma
  id: gamma
  parent: Genesis.Graphics.RenderSettings
  langs:
  - csharp
  - vb
  name: gamma
  nameWithType: RenderSettings.gamma
  fullName: Genesis.Graphics.RenderSettings.gamma
  type: Field
  assemblies:
  - Genesis
  namespace: Genesis.Graphics
  syntax:
    content: public float gamma
    return:
      type: System.Single
    content.vb: Public gamma As Single
- uid: Genesis.Graphics.RenderSettings.VirtualResolution
  commentId: F:Genesis.Graphics.RenderSettings.VirtualResolution
  id: VirtualResolution
  parent: Genesis.Graphics.RenderSettings
  langs:
  - csharp
  - vb
  name: VirtualResolution
  nameWithType: RenderSettings.VirtualResolution
  fullName: Genesis.Graphics.RenderSettings.VirtualResolution
  type: Field
  assemblies:
  - Genesis
  namespace: Genesis.Graphics
  syntax:
    content: public Vec3 VirtualResolution
    return:
      type: Genesis.Math.Vec3
    content.vb: Public VirtualResolution As Vec3
references:
- uid: Genesis.Graphics
  commentId: N:Genesis.Graphics
  isExternal: true
  href: Genesis.html
  name: Genesis.Graphics
  nameWithType: Genesis.Graphics
  fullName: Genesis.Graphics
  spec.csharp:
  - uid: Genesis
    name: Genesis
    isExternal: true
    href: Genesis.html
  - name: .
  - uid: Genesis.Graphics
    name: Graphics
    isExternal: true
    href: Genesis.Graphics.html
  spec.vb:
  - uid: Genesis
    name: Genesis
    isExternal: true
    href: Genesis.html
  - name: .
  - uid: Genesis.Graphics
    name: Graphics
    isExternal: true
    href: Genesis.Graphics.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: Genesis.Math.Vec3
  commentId: T:Genesis.Math.Vec3
  parent: Genesis.Math
  isExternal: true
  href: Genesis.Math.Vec3.html
  name: Vec3
  nameWithType: Vec3
  fullName: Genesis.Math.Vec3
- uid: Genesis.Math
  commentId: N:Genesis.Math
  isExternal: true
  href: Genesis.html
  name: Genesis.Math
  nameWithType: Genesis.Math
  fullName: Genesis.Math
  spec.csharp:
  - uid: Genesis
    name: Genesis
    isExternal: true
    href: Genesis.html
  - name: .
  - uid: Genesis.Math
    name: Math
    isExternal: true
    href: Genesis.Math.html
  spec.vb:
  - uid: Genesis
    name: Genesis
    isExternal: true
    href: Genesis.html
  - name: .
  - uid: Genesis.Math
    name: Math
    isExternal: true
    href: Genesis.Math.html
